<?php
require_once("include/config/condb.php");
require_once("include/interface/database_interface.php");
require_once("include/classes/picture.php");
require_once("include/classes/php.php");
require_once("include/classes/sql.php");
require_once("include/manupuator/data_manupuator.php");
require_once("include/classes/pager.php");
require_once("include/dataView/globalView.php");
require_once("include/htmlConfig/configure_html.php");?>